### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by goblockme** [tombusby/PolishCaseTrainer#6]
Hi, as a fellow Polish learner I love the project and would like to contribute to it. Would you still be interested in maintaining it?
Additionally, could you kindly add a license to the repository? I have some ideas for a separate project where I would use some code if possible - or continue to work on a fork on my own in case you're not interested in actively maintaining it anymore.

**Comment by tombusby** [comment]
https://github.com/tombusby/PolishCaseTrainer/blob/master/LICENSE

enjoy :)

I'd like to continue to work on this but haven't found much time.

feel free to use any source for whatever purpose.
